### ISSUE TITLE
dependency/files missing?

### ISSUE THREAD

**Issue by ajacobi15** [fengranMark/HAConvDR#1]
@fengranMark
Hello, I got a bit stuck trying to run the preprocessing part. I'm having trouble figuring out which files should match up in `preprocess_topicoqa.py`. Specifically, I'm not sure which topiocqa downloaded files match with:
- `gold_*.json`
- `../../../ConvDR-main/output/topiocqa/dense_rel/*_rel_label.json`
- `output/topiocqa/bm25/bm25_train_for_hardneg_res.trec`
and a few others

Also, haven't gotten around to `gen_doc_embeddings.py` because I'm still tangled up in the preprocessing step. But I did notice there seems to be no `models` file in the repo. This means every time it hits `from models import *`, it will come back with a `not found` error. Looks like it's messing up the imports for `load_model` and `ANCE` from what I've seen. Could it be that the `models.py` file wasn't uploaded or am I missing something?

Would really appreciate any help or pointers on this. Cheers!

**Comment by fengranMark** [comment]
Thank you for your messages. I have made them more clear.

1. The gold_*.json is from the original datasets.
2. This file should be generated in stage 2 and then run the corresponding preprocessing function again. I have revised the readme to make it clear.
3. This is generated after running the bm25 retrieval, and the rank-list is used for extract hard negative.

The models file is in src folder, I have modified the path.

**Comment by ajacobi15** [comment]
@fengranMark 
Thanks a lot for getting back to me so quickly! I'll give it another try based on these modifications. Just one thing though - after checking out the updates to `models.py`, it looks like the `load_model` function might still be missing?

**Comment by fengranMark** [comment]
@ajacobi15 Solved. Sorry for my mess up for different version.

**Comment by ajacobi15** [comment]
Thank you, closing the issue

**Comment by ajacobi15** [comment]
Hi @fengranMark
I would like to check with you how I can obtain `checkpoints/ad-hoc-ance-msmarco`?

**Comment by fengranMark** [comment]
> Hi @fengranMark I would like to check with you how I can obtain `checkpoints/ad-hoc-ance-msmarco`?

https://github.com/microsoft/ANCE
